apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: openshift-gitops 
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./applications/app2
    repoURL: https://github.com/yangcao77/demo-layout
    targetRevision: main
  destination:
    namespace: demo-layout
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

