apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: app1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: app1 
  name: app1
  namespace: demo-layout
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: app1 

