apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: app1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  app1
    app.kubernetes.io/part-of: demo-layout  
  name: app1
  namespace: demo-layout
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  app1 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  app1
    spec:
      containers:
      - image: quay.io/jduimovich0/bootstrap
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi    
        env:
        - name: GIT_REPO
          value: https://github.com/jduimovich/demo-layout


